disk_size: 8
datastore: Local-004
vmnic0_portgroup: VM Network
vmnic1_portgroup: PG-vMotion
vmnic2_portgroup: PG-Storage
vmnic3_portgroup: PG-Tenant
vmnic4_portgroup: PG-Public
memory_size : 4096
cpucount : 4
nfs_mount_dir_path: /mnt/nfs


cluster1_name           : Management Cluster
cluster1_host1_vmname   : HOST70-60U1
cluster1_host1_hostname : host70
cluster1_host2_vmname   : HOST071-60U1
cluster1_host2_hostname : host071
cluster2_name           : Edge Cluster
cluster2_host1_vmname   : HOST072-60U1
cluster2_host1_hostname : host072
cluster2_host2_vmname   : HOST073-60U1
cluster2_host2_hostname : host073
cluster3_name           : Compute Cluster
cluster3_host1_vmname   : HOST74-60U1
cluster3_host1_hostname : host074
cluster3_host2_vmname   : HOST075-60U1
cluster3_host2_hostname : host075
