- name: Add Hosts to Tenant dVS
  local_action:
    module: vmware_dvs_host
    hostname: "{{ inventory_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ item.1 }}"
    switch_name: "{{ tenant_dvs }}"
    vmnics:
        - vmnic3
    state: present
  with_subelements:
  - cluster_list
  - esxi.fqdn
  ignore_errors: yes

- name: Add Hosts to Public dVS
  local_action:
    module: vmware_dvs_host
    hostname: "{{ inventory_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
#    esxi_hostname: "{{ inventory_hostname }}"
    esxi_hostname: "{{ item.1 }}"
    switch_name: "{{ public_dvs }}"
    vmnics:
        - vmnic4
    state: present
  with_subelements:
  - cluster_list
  - esxi.fqdn
  ignore_errors: yes

