- name: Create Tenant-DVS dvswitch
  local_action:
    module: vmware_dvswitch
    hostname: "{{ inventory_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    datacenter_name: "{{ vcsa_datacenter }}"
    switch_name: "{{ tenant_dvs }}"
    mtu: 8000
    uplink_quantity: 4
    discovery_proto: lldp
    discovery_operation: both
    state: present
  ignore_errors: yes

- name: Create Public-DVS dvswitch
  local_action:
    module: vmware_dvswitch
    hostname: "{{ inventory_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    datacenter_name: "{{ vcsa_datacenter }}"
    switch_name: "{{ public_dvs }}"
    mtu: 8000
    uplink_quantity: 4
    discovery_proto: lldp
    discovery_operation: both
    state: present
  ignore_errors: yes

- name: Create Public portgroup
  local_action:
    module: vmware_dvs_portgroup
    hostname: "{{ inventory_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    portgroup_name: Public
    switch_name: "{{ public_dvs }}"
    vlan_id: 0
    num_ports: 128
    portgroup_type: earlyBinding
    state: present
  ignore_errors: yes
