- name: check if there is a nfs datastore
  raw: esxcli storage nfs list | grep NFS | awk  '{print $1}'
  register: result

- debug: var=result.stdout

- name: unmount nfs
  raw: esxcli storage nfs remove --volume-name=NFS-Remote1
  when: result.stdout.find ("NFS-Remote1") == 0

- name: check
  raw: esxcli storage nfs list
  register: result

- debug: var=result.stdout_lines
