#- name: Wait until vCSA is ready
#  action: shell sshpass -p {{ ansible_ssh_pass }} ssh root@{{ vcsa_ip_address }} "com.vmware.appliance.version1.services.status.get --name vmware-vpxd" -o 'StrictHostKeyChecking no'
#  register: result
#  until: result.stdout.find("up") != -1
#  retries: 500
#  delay: 30
#  become: True

- name: Wait until vCSA is ready
  local_action: wait_for port=9443 host="{{ item.value.vcsa_ip_address }}"  delay=10 timeout=3600
  with_dict: "{{ vcsa_config }}"

#- name: Confirm vCSA is ready
#  debug: msg="vmware-vpxd {{ result.stdout}}

