- name: Unmount the ISO
  mount: 
    name: "{{ iso_mount_dir_path }}" 
    src: "{{ vcsa_iso_path }}" 
    fstype: iso9660
    state: unmounted
  become: True

- name: Delete the mount directory
  file:
    path: "{{ iso_mount_dir_path }}"
    state: absent
    mode: 0755
  become: True

- name: Unmount NFS server
  local_action: mount name="{{ nfs_mount_dir_path }}" src={{ kickstart_nfs_server }}:{{ nfs_server_dir_path }} fstype=nfs  state=unmounted
  run_once: true
  become: True

- name: Delete NFS mount
  file: path="{{ nfs_mount_dir_path }}" state=absent mode=0755
  run_once: true
  become: True
