- name: Wait until hosts are ready
  local_action: wait_for port=443 host="{{ inventory_hostname }}"  delay=10 timeout=300

- name: Configure ESXi hostname and DNS servers
  local_action:
    module: vmware_dns_config
    hostname: "{{ inventory_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    change_hostname_to: "{{ hostsname }}"
    domainname: "{{ domain_name }}"
    dns_servers:
        - "{{ dns_server1 }}"
        - "{{ dns_server2 }}"

- name: Add Management Network VM Portgroup
  local_action:
    module: vmware_portgroup
    hostname: "{{ inventory_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    switch_name: vSwitch0
    portgroup_name: "VM Network"
    vlan_id: 0
  ignore_errors: yes

- name: Add vSwitch1
  local_action:
    module: vmware_vswitch
    hostname: "{{ inventory_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    switch_name: vSwitch1
    nic_name: vmnic1
    mtu: 8000
    state: present
  ignore_errors: yes

- name: Add vMotion vmkernel port (vmk1)
  local_action:
    module: vmware_vmkernel
    hostname: "{{ inventory_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    vswitch_name: vSwitch1
    portgroup_name: vMotion
    vlan_id: 0
    ip_address: "{{ vmotion_ip }}"
    subnet_mask: 255.255.255.0
    enable_mgmt: False
    enable_vmotion: True
    mtu: 8000
  ignore_errors: yes

- name: Add vSwitch2
  local_action:
    module: vmware_vswitch
    hostname: "{{ inventory_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    switch_name: vSwitch2
    nic_name: vmnic2
    mtu: 8000
    state: present
  ignore_errors: yes

- name: Add Storage vmkernel port (vmk2)
  local_action:
    module: vmware_vmkernel
    hostname: "{{ inventory_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    vswitch_name: vSwitch2
    portgroup_name: Storage
    vlan_id: 0
    ip_address: "{{ storage_ip }}"
    subnet_mask: 255.255.255.0
    enable_mgmt: False
    mtu: 8000
  ignore_errors: yes

