- name: Start VMs
  vsphere_guest:
   vcenter_hostname: "{{ vcenter_hostname }}"
   username: "{{ vcenter_username }}"
   password: "{{ vcenter_password }}"
   guest: "{{ inventory_hostname }}"
   cluster: "{{ vcenter_cluster }}"
   resource_pool: "{{ resource_pool }}"
   state: powered_on
