- name: Create VMs
  vsphere_guest:
   vcenter_hostname: "{{ vcenter_hostname }}"
   username: "{{ vcenter_username }}"
   password: "{{ vcenter_password }}"
   #guest: "{{ inventory_hostname }}"
   guest: "{{ item.0.name }}"
   cluster: "{{ vcenter_cluster }}"
   resource_pool: "/Resources/{{ esxi_resource_pool }}"
   state: present
#  vm_extra_config:
   vm_disk:
     disk1:
       size_gb: "{{ disk_size }}"
       type: thin
       #datastore: "{{ deploy_target_datastore }}" 
       #datastore: "{{ item.0.deploy_target_datastore }}"
       datastore: Local-003
   vm_nic:
     nic1:
       type: e1000
       network: "{{ vmnic0_portgroup }}"
       network_type: standard
     nic2:
       type: e1000
       network: "{{ vmnic1_portgroup }}"
       network_type: standard
     nic3:
       type: e1000
       network: "{{ vmnic2_portgroup }}"
       network_type: standard
     nic4:
       type: e1000
       network: "{{ vmnic3_portgroup }}"
       network_type: standard
     nic5:
       type: e1000
       network: "{{ vmnic4_portgroup }}"
       network_type: standard
   vm_hw_version: vmx-08
   vm_hardware:
     memory_mb: "{{ memory_size }}"
     num_cpus: "{{ cpucount }}"
     osid: vmkernel5Guest
     scsi: lsi
     vm_cdrom:
       type: "iso"
       iso_path: "{{ esxi_iso_path }}"
   esxi:
     datacenter: "{{ vm_datacenter }}"
     #hostname: "{{ deploy_target_esxi }}"
     hostname: "{{ item.0.deploy_target.esxi }}"
  with_subelements:
  - vm_list

- name: Confirm
  pause:
