- name: Create Datacenter
  local_action: >
        vmware_datacenter
        hostname="{{ item.value.vcsa_hostname}}"
        username="{{ vcsa_username }}"
        password="{{ vcsa_password }}"
        datacenter_name="{{ vcsa_datacenter }}"
        state=present
  ignore_errors: yes
  with_dict: "{{ vcsa_config }}"
