- name: Add ESXi Hosts to Management Cluster
  local_action:
    module: vmware_host
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    datacenter_name: "{{ vcsa_datacenter }}"
    cluster_name: "{{ vcsa_cluster1_name }}"
    esxi_hostname: "{{ inventory_hostname }}"
    esxi_username: "{{ esxi_username }}"
    esxi_password: "{{ esxi_password }}"
    state: present
  ignore_errors: yes



