- name: Add hosts to in-memory inventory
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  become: false
  connection: local
  user: remote
  vars_files:
   - /home/sotani/deploy-vsphere-cluster/vars/{{ project_name }}.yml
  tasks:
   - local_action: add_host name="{{ nfs_storage }}" 
     changed_when: False

- hosts: nfs-storage
  gather_facts: false
  any_errors_fatal: true
  become: false
  vars_files:
   - /home/sotani/deploy-vsphere-cluster/vars/{{ project_name }}.yml
  roles:
    - { role: configure-storage }
