- name: Add hosts to in-memory inventory
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  become: false
  connection: local
  user: remote
  vars_files:
   - /opt/ansible/deploy-vsphere-cluster/vars/{{ project_name }}.yml
  tasks:
   - local_action: add_host name="{{ item.value.mgmt_ip_addr }}" group=nested_esxi hostsname={{ item.value.hostsname }} vmotion_ip={{ item.value.vmotion_ip_addr }} storage_ip={{ item.value.storage_ip_addr }}
     with_dict: "{{ vm_config }}"
     changed_when: False

- hosts: nested_esxi
  gather_facts: false
  any_errors_fatal: true
  become: false
  connection: local
  user: remote
  vars_files:
   - /opt/ansible/deploy-vsphere-cluster/vars/{{ project_name }}.yml
  roles:
    - { role: configure-esxi }
