- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  sudo: false
  connection: local
  user: remote
  vars_files: 
   - /home/sotani/deploy-vsphere-cluster/vars/{{ project_name }}.yml
  roles:
    - { role: deploy-esxi }
