- hosts: vms
  gather_facts: false
  any_errors_fatal: true
  become: true
  connection: local
  user: remote
  vars_files:
   - /home/sotani/deploy-vsphere-cluster/vars/{{ project_name }}.yml
  roles:
    - { role: kickstart }
