- name: Add hosts to in-memory inventory
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  become: false
  connection: local
  user: remote
  vars_files:
   - "/opt/ansible/deploy-vsphere-cluster/vars/{{ project_name }}.yml"
  tasks:
   - local_action: add_host name="{{ item.key }}"
     with_dict: "{{ nesting_esxi }}"
     changed_when: False

- hosts: nesting_esxi
  gather_facts: false
  any_errors_fatal: true
  become: false
  vars_files:
   - "/opt/ansible/deploy-vsphere-cluster/vars/{{ project_name }}.yml"
  roles:
    - { role: mount-nfs }
