- include: mount-nfs.yml
- include: create-mgmt-esxi.yml
#- include: unmount-nfs.yml
- include: kickstart.yml
- include: start-vms.yml
- include: deploy-vcsa.yml
- include: datacenter.yml
- include: dvswitch.yml
- include: mgmt-cluster.yml
- include: mgmt-cluster-storage.yml
- include: adv-settings.yml
- include: create-edge-esxi.yml
#- include: edge-cluster.yml
#- include: compute-cluster1.yml
