- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  become: false
  connection: local
  user: remote
  vars_files:
   - /opt/ansible/deploy-vsphere-cluster/vars/{{ project_name }}.yml
  roles:
    - { role: datacenter }
