- name: Check software iSCSI status
  raw: esxcli iscsi software  get
  register: iscsi_status

- name: Enable software iSCSI
  raw: esxcli iscsi software set --enabled=true 
  when: iscsi_status.stdout.find ("false") != 1 
  register: iscsi_configuration

- name: Review software iSCSI configuration
  debug: var=iscsi_configuration.stdout_lines
  
- name: Check CHAP configuration status
  raw: esxcli iscsi adapter auth chap get --adapter=vmhba33
  register: chap_config_status

- name: Configure CHAP
  raw: esxcli iscsi adapter auth chap set --adapter=vmhba33 --authname="{{ iscsi_chap_authname }}" --direction=uni --level=required --secret="{{ iscsi_chap_secret }}"
  when: chap_config_status.stdout.find ("{{ iscsi_chap_authname }}") != 0

- name: Check CHAP configuration
  raw: esxcli iscsi adapter auth chap get --adapter=vmhba33
  register: chap_config_status

- name: Review CHAP configuration
  debug: var=chap_config_status.stdout_lines

- name: Add a dynamic discovery address
  raw: esxcli iscsi adapter discovery sendtarget add --address="{{ iscsi_storage }}":3260 --adapter=vmhba33

- name: Check sendtarget configuration
  raw: esxcli iscsi adapter discovery  sendtarget list
  register: sendtarget_configuration

- debug: var=sendtarget_configuration.stdout_lines

- name: Rescan
  raw: esxcli storage core adapter rescan --adapter vmhba33


